services:
  # Development service
  dev:
    build:
      context: .
      target: build
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - '7777:7777' # Custom development port
    command: pnpm run dev
    environment:
      - NODE_ENV=development
      - HOSTNAME=0.0.0.0
      - PORT=7777
      - NEXT_PUBLIC_GITHUB_TOKEN=${NEXT_PUBLIC_GITHUB_TOKEN:-}
    networks:
      - sortvision_net
    stdin_open: true
    tty: true

  # Production service - now uses Next.js server instead of nginx
  prod:
    build: .
    ports:
      - '3000:3000' # Changed from port 80 to 3000 for Next.js server
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
      - NEXT_PUBLIC_GITHUB_TOKEN=${NEXT_PUBLIC_GITHUB_TOKEN:-}
    networks:
      - sortvision_net
    restart: unless-stopped

  # Build service for testing builds locally
  build:
    build:
      context: .
      target: build
    volumes:
      - ./.next:/app/.next # Changed from ./dist to ./.next
    command: pnpm run build
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_GITHUB_TOKEN=${NEXT_PUBLIC_GITHUB_TOKEN:-}
    networks:
      - sortvision_net

networks:
  sortvision_net:
    driver: bridge
